spring:
  profiles:
    active: dev   #选dev中的配置
  application:
    name: microservice-springcloud-product-config
---
server:
  port: 8080
spring:
  profiles: dev
 
---
server:
  port: 8000
spring:
  profiles: prod